### ISSUE TITLE
ToDos

### ISSUE THREAD

**Issue by TariqAHassan** [tylercroberts/rGenius#15]
List of things left to do:

* Add API key so TravisCI can pass ✅ 
* Complete tests  ✅ 
* Finish Code Documentation  ✅ 
* Write vignette  ✅ 
* Add code to used to generate the plots in the README  ✅

**Comment by DuongVu39** [comment]
I already added the vignette here in this commit: https://github.com/tylercroberts/rGenius/commit/9b7d8a480b10ebd73b3fb99bd6bf5871c9f3d676

**Comment by TariqAHassan** [comment]
@DuongVu39 

This was published one day before that commit :)

(But yeah, I've crossed it off the list).
